// Generated by CoffeeScript 1.4.0
(function() {
  var root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof global !== "undefined" && global !== null ? global : window;

  root.StartAnchor = (function(_super) {

    __extends(StartAnchor, _super);

    function StartAnchor(debug) {
      StartAnchor.__super__.constructor.apply(this, arguments);
    }

    StartAnchor.prototype.matches = function(state) {
      if (state.input[state.currentPosition - 1] === StartGuard) {
        return Result.Success(state.currentPosition);
      } else {
        return Result.Failure();
      }
    };

    return StartAnchor;

  })(BasicToken);

  root.EndAnchor = (function(_super) {

    __extends(EndAnchor, _super);

    function EndAnchor(debug) {
      EndAnchor.__super__.constructor.apply(this, arguments);
    }

    EndAnchor.prototype.matches = function(state) {
      if (state.input[state.currentPosition] === EndGuard) {
        return Result.Success(state.currentPosition);
      } else {
        return Result.Failure();
      }
    };

    return EndAnchor;

  })(BasicToken);

  root.WordBoundary = (function(_super) {

    __extends(WordBoundary, _super);

    function WordBoundary(debug, negated) {
      this.negated = negated != null ? negated : false;
      WordBoundary.__super__.constructor.call(this, debug);
      this.wordClass = new WordClass();
    }

    WordBoundary.prototype.matches = function(state) {
      var leftChar, rightChar;
      leftChar = state.input[state.currentPosition - 1];
      rightChar = state.input[state.currentPosition];
      if ((this.wordClass.isInClass(leftChar) !== this.wordClass.isInClass(rightChar)) !== this.negated) {
        return Result.Success(state.currentPosition);
      } else {
        return Result.Failure();
      }
    };

    return WordBoundary;

  })(BasicToken);

}).call(this);
