// Generated by CoffeeScript 1.4.0
(function() {
  var root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof global !== "undefined" && global !== null ? global : window;

  root.Character = (function(_super) {

    __extends(Character, _super);

    function Character(debug, character) {
      this.character = character;
      Character.__super__.constructor.call(this, debug);
    }

    Character.prototype.reset = function() {
      Character.__super__.reset.call(this);
      return this.attempted = false;
    };

    Character.prototype.nextMatch = function(state, report) {
      if (this.attempted) {
        this.reset();
        return false;
      }
      if (state.input[state.currentPosition] === this.character) {
        this.attempted = true;
        return state.currentPosition + 1;
      }
      return false;
    };

    return Character;

  })(root.Token);

}).call(this);
