// Generated by CoffeeScript 1.4.0
(function() {
  var root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof global !== "undefined" && global !== null ? global : window;

  root.Character = (function(_super) {

    __extends(Character, _super);

    function Character(debug, character) {
      this.character = character;
      Character.__super__.constructor.call(this, debug);
    }

    Character.prototype.reset = function(state) {
      Character.__super__.reset.apply(this, arguments);
      return state.tokens[this.debug.id].matchedPosition = null;
    };

    Character.prototype.setupStateObject = function() {
      var obj;
      obj = Character.__super__.setupStateObject.apply(this, arguments);
      obj.matchedPosition = null;
      return obj;
    };

    Character.prototype.matches = function(state) {
      if (state.input[state.currentPosition] === this.character) {
        state.tokens[this.debug.id].matchedPosition = state.currentPosition;
        return Result.Success(state.currentPosition + 1);
      } else {
        return Result.Failure();
      }
    };

    return Character;

  })(BasicToken);

}).call(this);
