// Generated by CoffeeScript 1.4.0
(function() {
  var root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof global !== "undefined" && global !== null ? global : window;

  root.Group = (function(_super) {

    __extends(Group, _super);

    function Group(debug, token, index) {
      this.index = index;
      Group.__super__.constructor.call(this, debug, token);
    }

    Group.prototype.reset = function() {
      Group.__super__.reset.call(this);
      this.result = 0;
      return this.firstPosition = false;
    };

    Group.prototype.nextMatch = function(state, report) {
      var result;
      if (this.result !== 0) {
        result = this.result;
        if (result === false) {
          this.reset();
        } else {
          this.result = 0;
        }
        return result;
      }
      if (this.firstPosition === false) {
        this.firstPosition = state.currentPosition;
      }
      result = this.subtokens[0].nextMatch(state, report);
      switch (result) {
        case 0:
        case -1:
          return result;
        case false:
          this.result = false;
          state.captures[this.index] = void 0;
          return 0;
        default:
          state.captures[this.index] = state.input.slice(this.firstPosition, result).join("");
          this.result = result;
          return -1;
      }
    };

    return Group;

  })(root.Token);

}).call(this);
