// Generated by CoffeeScript 1.4.0
(function() {
  var root;

  root = typeof global !== "undefined" && global !== null ? global : window;

  root.Inactive = "inactive";

  root.Active = "active";

  root.Matched = "matched";

  root.Failed = "failed";

}).call(this);
