// Generated by CoffeeScript 1.4.0
(function() {
  var root;

  root = typeof global !== "undefined" && global !== null ? global : window;

  root.StartGuard = {};

  root.EndGuard = {};

}).call(this);
