// Generated by CoffeeScript 1.4.0
(function() {
  var root;

  root = typeof global !== "undefined" && global !== null ? global : window;

  root.Matcher = (function() {

    function Matcher(regex, nGroups, subject) {
      this.regex = regex;
      this.subject = subject;
      this.success = false;
      this.state = Matcher.setupInitialState(this.subject);
      this.regex.register(this.state);
    }

    Matcher.setupInitialState = function(subject) {
      var state;
      state = {
        input: this.parseInput(subject),
        startingPosition: 1,
        currentPosition: 1,
        tokens: [],
        captures: []
      };
      return state;
    };

    Matcher.parseInput = function(inputString) {
      var input;
      input = [StartGuard].concat(inputString.split(""));
      input.push(EndGuard);
      return input;
    };

    Matcher.prototype.stepForward = function() {
      var result;
      result = this.regex.nextMatch(this.state);
      switch (result.type) {
        case Failure:
          this.state.currentPosition = ++this.state.startingPosition;
          this.regex.reset(this.state);
          return this.state.startingPosition < this.state.input.length;
        case Indeterminate:
          return true;
        case Success:
          this.success = true;
          return false;
      }
    };

    Matcher.prototype.group = function(n) {
      if (n == null) {
        n = 0;
      }
      return this.state.captures[n];
    };

    Matcher.prototype.groups = function() {
      return this.state.captures;
    };

    return Matcher;

  })();

}).call(this);
